= Последний пост

:toc:

== Что такое ?


HubPress is a free, open source tool you can use to build a rich, AsciiDoc based blog using GitHub Pages!

Created and maintained by http://github.com/anthonny[Anthonny Quérouil] (twitter http://twitter.com/anthonny_q[@anthonny_q]).

NOTE: While HubPress may appear feature-complete, it is actually in Tech Preview. Bugs are inevitible, so if you find something is not behaving the way you think it should, please raise a bug and the project team will address it as soon as possible.

Documentation is rapidly evolving as the project gains momentum. Check back regularly for more tips on how to use HubPress. If you see something wrong with the documentation, please raise a bug. Your help with improving every aspect of HubPress is greatly appreciated. Pull Requests are *always* welcome.

== Browser compatibility

HubPress is compatible with Chrome Desktop, Firefox Desktop, and Chrome for Android.

Chrome Beta for Android will be fully compatible soon, but is not currently supported because of bugs with IndexedDB. While using HubPress Preview, use Chrome for Android only.

NOTE: Просто заметка